
#- name: Install python-influxdb package
#  become: yes
#  pip:
#    name: influxdb
#    state: present
#
#- name: Create database using custom credentials
#  influxdb_database:
#      hostname: "{{influxdb_ip_address}}"
#      username: "{{influxdb_username}}"
#      password: "{{influxdb_password}}"
#      database_name: "{{influxdb_database_name}}"

- name: create admin user for all influxdb databases
  shell: "curl -G http://localhost:8086/query --data-urlencode \"u={{ influxdb_admin_user }}\" --data-urlencode \"p={{ influxdb_admin_password }}\" --data-urlencode \"q=CREATE USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}' WITH ALL PRIVILEGES\""

- name: create influxdb database
  shell: "curl -G http://localhost:8086/query --data-urlencode \"u={{ influxdb_admin_user }}\" --data-urlencode \"p={{ influxdb_admin_password }}\" --data-urlencode \"q=CREATE DATABASE {{ influxdb_database }}\""

- name: create user for influxdb database
  shell: "curl -G http://localhost:8086/query --data-urlencode \"u={{ influxdb_admin_user }}\" --data-urlencode \"p={{ influxdb_admin_password }}\" --data-urlencode \"q=CREATE USER {{ influxdb_dbuser }} WITH PASSWORD {{ influxdb_dbpassword }}\""

- name: grant privileges to user for influxdb database
  shell: "curl -G http://localhost:8086/query --data-urlencode \"u={{ influxdb_admin_user }}\" --data-urlencode \"p={{ influxdb_admin_password }}\" --data-urlencode \"q=GRANT ALL ON {{ influxdb_database }} TO {{ influxdb_dbuser }}\""
