---
- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: present
  tags:
    - influxdb

- name: Download version when python >= 2.7.9
  get_url:
    url: "{{ influxdb_dl_url }}"
    dest: "{{ influxdb_pkg }}"
    checksum: "md5:{{ influxdb_md5_checksum }}"
  when: ansible_python_version|version_compare('2.7.9', '>=')
  tags:
    - influxdb

- name: Install curl when python < 2.7.9
  apt:
    name: curl
    state: present
  when: ansible_python_version|version_compare('2.7.9', '<')
  tags:
    - influxdb

- name: Download version when python < 2.7.9
  command: curl -o "{{ influxdb_pkg }}" "{{ influxdb_dl_url }}"
  args:
    creates: "{{ influxdb_pkg }}"
  when: ansible_python_version|version_compare('2.7.9', '<')
  tags:
    - influxdb
    - skip_ansible_lint

- name: Install package
  command: "dpkg --skip-same-version -i {{ influxdb_pkg }}"
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  when: ansible_distribution in ['Ubuntu', 'Debian']
  tags:
    - influxdb
